# https://github.com/marketplace/actions/labeler
---
"scope: project":
  - ./*
"scope: ci":
  - .github/**/*
"scope: sources":
  - src/main/**/*
"scope: tests":
  - src/test/**/*
"scope: integration tests":
  - src/it/**/*
