---
name: Stage

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  stage:
    runs-on: ubuntu-latest
    environment: staging
    name: Deploy and release snapshot
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Set up Java 11
        uses: actions/setup-java@v3.8.0
        with:
          distribution: adopt
          java-version: 11
          cache: maven
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_TOKEN
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE

      - name: Get current project version
        id: currentVersion
        uses: QwerMike/xpath-action@v1
        with:
          filename: pom.xml
          expression: '/*[local-name()="project"]/*[local-name()="version"]/text()'

      - name: Deploy snapshot to OSSRH
        if: endsWith(steps.currentVersion.outputs.result, '-SNAPSHOT')
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: mvn deploy jacoco:report -Pprepare-deployment,sign-deployment,deploy-ossrh -B -ff

      - name: Upload integration test logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: it-logs
          path: target/it/simple-custom-skill-it/build.log
          if-no-files-found: warn

      - name: Push coverage report
        uses: codecov/codecov-action@v3
        with:
          file: target/site/jacoco/jacoco.xml
